# Generated by Django 3.2.16 on 2024-11-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id', '-pub_date'), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
