# Generated by Django 5.1.3 on 2024-12-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='post_id',
        ),
    ]
